name: L3MEG-GH-TP3
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=2
  - nodejs
  - nbresuse
  - psutil
  - pip
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse
  # - jupyter_contrib_nbextensions
  - ipyigv
  - pip:
    - bash_kernel
